development:
  adapter: mysql2
  database: ror
  pool: 5
  username: root
  password: vsspl
  timeout: 5000

test:
  adapter: mysql2
  database: ror
  pool: 5
  username: root
  password: vsspl
  timeout: 5000

production:
  adapter: postgresql
  pool: 5
  timeout: 5000
